### ISSUE TITLE
Page issue

### ISSUE THREAD

**Issue by Prosp3r** [michael-001/debusy#2]
1. Rounded edge is too round it should be slightly sharper.
2. Color is not consistent with the one in the design i.e. 90% of  #F6C400
3. Date widget not working
4. Edge of tab on design is not rounded
5. Space between form element border and icon is not proportionate with design(too close) please measure the actual pixel distance
6. Design of Radio button is not consistent with design
7. Borders of form elements on design is black not grey
8. Page scrolls left to right

**Comment by michael-001** [comment]
issues resolved.
